### ISSUE TITLE
[domestic/regional] tooltip の感度が微妙

### ISSUE THREAD

**Issue by riantkb** [riantkb/icpc_standing_colorizer#1]
チームレートを表す円の上にカーソルを合わせるとレートが表示されるが、ちょっと待たないと表示されない
AtCoder Problems と同じようなスタイルで表示されると嬉しい気もするが、どこでスタイル等を調整するのかわからず

**Comment by TumoiYorozu** [comment]
円に 適当な class を付けて（直接いじるのが大変なら div でくくってもいい）、
それの hover 要素をつけると良さそう

https://www.jungleocean.com/programming/190308tooltip-css

**Comment by TumoiYorozu** [comment]
↑、明日辺り手を入れるかも

**Comment by riantkb** [comment]
#5 でいい感じになった

**Comment by riantkb** [comment]
- [x] ホバーはチーム名ではなく円の方についていた方が良さそう？
- [x] https://icpc.iisf.or.jp/past-icpc/domestic2021/common/guest_standings_ja.php.html とかの方も同じようにしたい

**Comment by riantkb** [comment]
https://icpc.iisf.or.jp/past-icpc/domestic2021/common/guest_standings_ja.php.html とかでの tooltip の位置がちょっと微妙だけど当初の目的は達成されたので閉じます
