### ISSUE TITLE
[regional] 学内順位が更新されたときに userscript が入っていると更新されない

### ISSUE THREAD

**Issue by riantkb** [riantkb/icpc_standing_colorizer#2]
https://twitter.com/rian_tkb/status/1503894699035488256

こまった

**Comment by TumoiYorozu** [comment]
`<small>` でメンバーをくくると、大学名・順位のところも `<small>` なので、path がズレて壊れてそう（憶測）

コーチの名前入れ無いなら、`<small>` 使わなくても良い気がしてます。

**Comment by riantkb** [comment]
あーなるほど、div.span.small みたいな感じで指定しているとすると壊れる、ってことか
そういうことをしているかはかなり微妙な気もしているけど、small をなくしてみても良いのはそうっぽい
（追記： #4 もあるし small を取ると三人目のチームメンバーの名前が切れるみたいなことはありそう）

**Comment by TumoiYorozu** [comment]
実はチーム名のところを、ツールチップ表示の都合で `overflow = "visible";` に改造したので、「名前が切れる」ことは発生しなくなった。
（代わりに A問題に被る可能性はあるけど、A問題の情報なんて興味ないよね🤔🤔🤔）

https://github.com/riantkb/icpc_standing_colorizer/pull/5/files#diff-1c3bf82acb1869a0e46a0f753fa76cbad1ecebc13aa48e56b13cafee709c1998R209

**Comment by riantkb** [comment]
#10 により一応解決

**Comment by riantkb** [comment]
順位表側の形式変更により解決されていたので以下で戻した
a0e2f74600b4aed1c6c65586c991f3d16568ed4f
